### PR TITLE
Add e2e tests using Jest

### PR DESCRIPTION
**Pull request by abdulhannanali**
### Summary
This PR adds e2e tests based on the minimal example for `react-context-props` included, enzyme is used for mounting and traversing the React component. Using Jest as the testing framework.

### Why tests?

This repo is simple enough to not contain tests as you mention, but I still think at least automated e2e tests based on the same example would be helpful which can run on each PR and will make life easier for maintainers, cos they won't have to run and test example for each PR manually. 

Not adding unit tests

### Test plan

Code is linted, all tests are passing :tada:

### CODE REVIEW

**Comment by abdulhannanali** [comment]
Contains a pre configured Travis CI file, you'll just have to enable it for the repo.

**Comment by xaviervia** [comment]
Wow, awesome job! Thanks a lot. I was just doing some API changes in parallel, I will merge and add those examples as well.

**Comment by abdulhannanali** [comment]
@xaviervia I made a mistake and forgot to put `jest` in the `test` script in package.json, the current environment is not testing right now. Also, upgrading the sagui version, caused some problems, so I have to downgrade it, as it's not performing linting, as well as there are problems `babel-jest` is facing on this version.

**Comment by abdulhannanali** [comment]
@xaviervia Making a new PR with these changes.

**Pull request merged**
